// test - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/test_config.h"
#include "generated/test_init.h"

#include <rex/rex_app.h>

#include <rex/filesystem/devices/host_path_device.h>
#include <rex/filesystem/vfs.h>

class TestApp : public rex::ReXApp
{
public:
	using rex::ReXApp::ReXApp;

	static std::unique_ptr<rex::ui::WindowedApp> Create(
		rex::ui::WindowedAppContext& ctx)
	{
		return std::unique_ptr<TestApp>(new TestApp(ctx, "test",
			{ PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
			 PPC_IMAGE_SIZE, PPCFuncMappings }));
	}

protected:
	virtual void OnPostSetup() override
	{
		rex::Runtime* _runtime = rex::ReXApp::ReXApp::runtime();

#if 0
		// Load XEX image
		auto status = _runtime->LoadXexImage("game:\\halo3_cache_release.xex");
		if (XFAILED(status))
		{
			REXLOG_ERROR("Failed to load XEX: {:08X}", status);
			return;
		}
#endif

		auto mount_path = "\\Device\\Harddisk0\\Partition1";
		auto device = std::make_unique<rex::filesystem::HostPathDevice>(mount_path,
			_runtime->game_data_root(), false);
		if (!device->Initialize())
		{
			REXKRNL_ERROR("Runtime::SetupVfs: Failed to initialize host path device");
			return;
		}

		rex::filesystem::VirtualFileSystem* _file_system = _runtime->file_system();

		if (!_file_system->RegisterDevice(std::move(device)))
		{
			REXKRNL_ERROR("Runtime::SetupVfs: Failed to register host path device");
			return;
		}
		REXKRNL_INFO("  Mounted {} at {}", _runtime->game_data_root().string(), mount_path);

		// Register symbolic links for cache:
		_file_system->RegisterSymbolicLink("cache:", mount_path);

	}
};

REX_DEFINE_APP(test, TestApp::Create)
