// halo3_cache_release - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/halo3_cache_release_config.h"
#include "generated/halo3_cache_release_init.h"

#include <rex/rex_app.h>

#include <rex/filesystem/devices/host_path_device.h>
#include <rex/filesystem/vfs.h>

class Halo3CacheReleaseApp : public rex::ReXApp
{
public:
	using rex::ReXApp::ReXApp;

	static std::unique_ptr<rex::ui::WindowedApp> Create(
		rex::ui::WindowedAppContext& ctx)
	{
		return std::unique_ptr<Halo3CacheReleaseApp>(new Halo3CacheReleaseApp(ctx, "halo3_cache_release",
			{ PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
			 PPC_IMAGE_SIZE, PPCFuncMappings }));
	}

protected:
	virtual void OnLoadXexImage(std::string& xex_image) override;
	virtual void OnPostSetup() override;
	virtual void OnConfigurePaths(rex::PathConfig& paths) override;
};

REX_DEFINE_APP(halo3_cache_release, Halo3CacheReleaseApp::Create)

void Halo3CacheReleaseApp::OnLoadXexImage(std::string& xex_image)
{
	xex_image = "game:\\halo3_cache_release.xex";
}

void Halo3CacheReleaseApp::OnPostSetup()
{
	rex::Runtime* _runtime = rex::ReXApp::ReXApp::runtime();
	rex::filesystem::VirtualFileSystem* fs = _runtime->file_system();

	auto cache_device = std::make_unique<rex::filesystem::HostPathDevice>(
		"\\CACHE", _runtime->game_data_root(), false);
	if (!cache_device->Initialize())
	{
		REXFS_ERROR("Unable to scan cache path");
	}
	else
	{
		if (!fs->RegisterDevice(std::move(cache_device)))
		{
			REXFS_ERROR("Unable to register cache path");
		}
		else
		{
			fs->RegisterSymbolicLink("cache:", "\\CACHE");
		}
	}

	auto xstorage_device = std::make_unique<rex::filesystem::HostPathDevice>(
		"\\XSTORAGE", _runtime->game_data_root() / "xstorage", false);
	if (!xstorage_device->Initialize())
	{
		REXFS_ERROR("Unable to scan xstorage path");
	}
	else
	{
		if (!fs->RegisterDevice(
			std::move(xstorage_device)))
		{
			REXFS_ERROR("Unable to register xstorage path");
		}
		else
		{
			fs->RegisterSymbolicLink("xstorage:",
				"\\XSTORAGE");
		}
	}
}

void Halo3CacheReleaseApp::OnConfigurePaths(rex::PathConfig& paths)
{
	paths.game_data_root = ".";
	paths.user_data_root = ".";
	paths.update_data_root = ".";
}
